"""content item media url

Revision ID: 0032
Revises: 0031
Create Date: 2026-08-10

Instagram's real API has no text-only post — every publish there needs an
actual image/video. `ContentItem` had no media field at all, so no
Instagram publish could ever succeed regardless of config. Adds a
user-attached media URL per item (set via POST .../media, not generated by
this app).
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0032"
down_revision = "0031"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column("content_items", sa.Column("media_url", sa.String(), nullable=True))


def downgrade() -> None:
    op.drop_column("content_items", "media_url")
